version: '3'
services:
  postgres-db:
    image: 'postgres:14-alpine'
    container_name: "your-books-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=your-books
    ports:
      - 5432:5432
    network_mode: "host"
  app:
    image: your-books:latest
    container_name: your-books-server
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/your-books
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - postgres-db

